# thangdz-term — main config file (symlinked to ~/.zshrc)
# After editing, run `reload` or open a new terminal to apply.

# Auto-detect the repo directory via the ~/.zshrc symlink
_my_zsh_rc="${(%):-%N}"
export THANGDZ="${_my_zsh_rc:A:h}"
unset _my_zsh_rc
# If you copy this file instead of symlinking, set it manually:
# export THANGDZ="$HOME/.thangdz-term"
[[ -f "$THANGDZ/init.zsh" ]] || export THANGDZ="$HOME/.thangdz-term"

# Theme (themes/<name>.zsh)
ZSH_THEME="default"

# Plugins (plugins/<name>/, see init.zsh for the loading order)
plugins=(zsh-autosuggestions zsh-syntax-highlighting)

# Load the framework
source "$THANGDZ/init.zsh"

# ==================== Personal config ====================

alias pj="cd ~/Projects"

# Added by Antigravity / Antigravity IDE
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"
export PATH="$HOME/.antigravity-ide/antigravity-ide/bin:$PATH"

# BEGIN ServBay Environment Block (auto-generated by ServBay — do not edit)
export PATH="/Applications/ServBay/script/alias:/Applications/ServBay/bin:/Applications/ServBay/sbin:/Applications/ServBay/script:/Applications/ServBay/package/node/current/bin:/Applications/ServBay/package/go/current/bin:$PATH"
export PATH=$PATH:$(go env GOPATH)/bin
# END ServBay Environment Block
